version: '3.3'
services:
    postgres:
        image: sameersbn/postgresql:latest
        container_name: pgsql_silvernext
        ports:
            - '5432:5432'
        env_file:
            - ./.env.local
        volumes:
            - ./../data/postgres:/var/lib/postgresql/data
    redis:
        image: redis:latest
        container_name: redis_silvernext
        ports:
            - '6379:6379'
        env_file:
            - ./.env.local
        volumes:
            - ./../data/redis:/var/lib/redis/data
